SPLIT_KEYBOARD = yes

OLED_ENABLE = no
OLED_DRIVER = ssd1306

BOOTLOADER = caterina

EXTRAKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
MOUSEKEY_ENABLE = yes
SEND_STRING_ENABLE = yes
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
LEADER_ENABLE = yes

COMMAND_ENABLE = no
ENCODER_ENABLE = no
AUDIO_ENABLE = no
MUSIC_ENABLE = no
HAPTIC_ENABLE = no
RGB_MATRIX_ENABLE = no
VIA_ENABLE = no
LTO_ENABLE = yes
