BOOTLOADER = rp2040

ENCODER_ENABLE = no
EXTRAKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
MOUSEKEY_ENABLE = no
SEND_STRING_ENABLE = yes
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes
LAYER_LOCK_ENABLE = yes

AUDIO_ENABLE = no
MUSIC_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

HAPTIC_ENABLE = no

RGB_MATRIX_ENABLE = no

VIA_ENABLE = no

LTO_ENABLE = yes
